CREATE TABLE IF NOT EXISTS USER (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    password TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    created_by TIMESTAMP DEFAULT 'SYSTEM',
    -- created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by TIMESTAMP DEFAULT 'SYSTEM'
    -- updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
